version: '3.5'

services:
  db_users:
    container_name: db_users
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=admin
      - POSTGRES_DB=POSTGRES
    image: postgres:14.3-alpine
  redis_posts:
    container_name: redis_posts
    ports:
      - "6379:6379"
    image: redis:7.2