version: '3.5'

services:
  db_auth:
    container_name: db_auth
    ports:
      - "5432:5432"
    environment:
      - POSTGRESS_PASSWORD=root
      - POSTGRESS_USER=admin
    image: postgres:14.3-alpine